services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leveza
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - leveza_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d leveza']
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  leveza_pgdata:
