import { StyleSheet } from 'react-native';
import { palette, typography } from '../theme';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 16,
    gap: 16,
  },
  headerCopy: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingTop: 0,
  },
  screenTitle: {
    fontFamily: typography.fontFamilyExtraBold,
    fontSize: 28,
    color: palette.textPrimary,
  },
  screenSubtitle: {
    marginTop: 4,
    color: palette.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: 15,
  },
  saveButton: {
    minHeight: 40,
    minWidth: 76,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
  },
  saveButtonActive: {
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  saveButtonDisabled: {
    opacity: 0.65,
  },
  saveButtonText: {
    color: palette.textMuted,
    fontFamily: typography.fontFamilyBold,
    fontSize: 14,
  },
  saveButtonTextActive: {
    color: palette.textInverse,
  },
  summaryCard: {
    marginBottom: 14,
    gap: 16,
  },
  summaryHeader: {
    gap: 4,
  },
  summaryTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  summaryIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E0F2FE',
  },
  summaryIconWarning: {
    backgroundColor: palette.warningBg,
  },
  summaryTitleGroup: {
    flex: 1,
    gap: 2,
  },
  summaryTitle: {
    color: palette.textPrimary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 17,
  },
  summaryEyebrow: {
    color: palette.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    lineHeight: 18,
  },
  pillWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  summaryPill: {
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: palette.cardSecondary,
    borderWidth: 1,
    borderColor: palette.border,
  },
  summaryPillPrimary: {
    backgroundColor: '#E0F2FE',
    borderColor: '#BAE6FD',
  },
  summaryPillWarning: {
    backgroundColor: palette.warningBg,
    borderColor: '#FDE68A',
  },
  summaryPillText: {
    color: palette.textPrimary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 13,
  },
  summaryPillTextPrimary: {
    color: palette.primaryDark,
  },
  summaryPillTextWarning: {
    color: '#92400E',
  },
  summaryRows: {
    gap: 8,
  },
  summaryRow: {
    minHeight: 38,
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: palette.cardSecondary,
  },
  summaryRowText: {
    color: palette.textPrimary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 14,
  },
  usuallyText: {
    marginTop: 4,
    color: palette.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    lineHeight: 20,
  },
  summaryBody: {
    color: palette.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    lineHeight: 20,
  },
  equipmentSummary: {
    color: palette.textPrimary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 18,
  },
  cardAction: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 2,
  },
  cardActionText: {
    color: palette.primary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 15,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  },
  backButtonText: {
    color: palette.primary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 15,
  },
  editorSection: {
    gap: 16,
  },
  editorIntro: {
    color: palette.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 2,
  },
  editorLabel: {
    marginTop: 6,
    color: palette.textPrimary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 15,
  },
  levelContainer: {
    gap: 10,
  },
  levelCard: {
    padding: 16,
    borderRadius: 14,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
  },
  levelCardSelected: {
    backgroundColor: '#E0F2FE',
    borderColor: palette.primary,
  },
  levelLabel: {
    fontSize: 16,
    fontFamily: typography.fontFamilyBold,
    color: palette.textPrimary,
    marginBottom: 4,
  },
  levelLabelSelected: {
    color: palette.primaryDark,
  },
  levelDescription: {
    fontSize: 13,
    color: palette.textSecondary,
    lineHeight: 18,
    fontFamily: typography.fontFamily,
  },
  textInput: {
    minHeight: 52,
    backgroundColor: palette.card,
    borderRadius: 14,
    padding: 16,
    color: palette.textPrimary,
    fontSize: 16,
    borderWidth: 1,
    borderColor: palette.border,
    fontFamily: typography.fontFamily,
  },
  targetList: {
    gap: 12,
  },
  targetEditorCard: {
    gap: 14,
    padding: 16,
    borderRadius: 16,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
  },
  targetEditorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  targetEditorCopy: {
    gap: 3,
  },
  targetEditorTitle: {
    color: palette.textPrimary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 16,
  },
  targetEditorMeta: {
    color: palette.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: 13,
  },
  stepperGrid: {
    gap: 10,
  },
  stepperRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  stepperLabel: {
    flex: 1,
    color: palette.textSecondary,
    fontFamily: typography.fontFamilyBold,
    fontSize: 13,
  },
  stepperControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rangeButton: {
    minWidth: 42,
    minHeight: 42,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  rangeValue: {
    minWidth: 34,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: typography.fontFamilyBold,
    color: palette.textPrimary,
  },
  weekPreferenceList: {
    gap: 10,
  },
  preferenceRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
  },
  preferenceCopy: {
    flex: 1,
    gap: 3,
  },
  preferenceDay: {
    fontSize: 14,
    fontFamily: typography.fontFamilyBold,
    color: palette.textPrimary,
  },
  preferenceBlocks: {
    fontSize: 13,
    fontFamily: typography.fontFamily,
    color: palette.textSecondary,
  },
  preferenceBadge: {
    alignSelf: 'center',
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#E0F2FE',
    color: palette.primaryDark,
    fontFamily: typography.fontFamilyBold,
    fontSize: 11,
  },
  inputActionRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  inputWithAction: {
    flex: 1,
  },
  addButton: {
    minWidth: 70,
    paddingVertical: 0,
    paddingHorizontal: 16,
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minHeight: 8,
  },
  removableTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.card,
    paddingVertical: 8,
    paddingLeft: 14,
    paddingRight: 10,
    borderRadius: 999,
    gap: 8,
    borderWidth: 1,
    borderColor: palette.border,
  },
  removableTagText: {
    color: palette.textPrimary,
    fontSize: 14,
    fontFamily: typography.fontFamily,
  },
  removeText: {
    color: palette.textMuted,
    fontSize: 20,
    fontWeight: '300',
    lineHeight: 20,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  emptyCard: {
    gap: 8,
  },
  bottomSpacer: {
    height: 110,
  },
});
