export {
  DEFAULT_LIBRARY_PATH,
  ExerciseLibraryError,
  openExerciseLibrary,
  type OpenExerciseLibraryOptions,
} from './lib/open-library.js';

export type {
  CandidateDiagnostics,
  CandidateQuery,
  CandidateResult,
  CanonicalExerciseRecord,
  EnvironmentConstraints,
  ExerciseLibrary,
  ExerciseLibraryMetadata,
  ExerciseRecord,
  ExerciseRole,
  ExperienceLevel,
  LoadLevel,
  MetadataCompleteness,
  WorkoutCatalogBlock,
  WorkoutCatalogDecision,
  WorkoutCatalogDiagnostics,
  WorkoutCatalogEnergy,
  WorkoutCatalogMaterializedPlan,
  WorkoutCatalogMatch,
  WorkoutCatalogQuery,
  WorkoutCatalogRecipe,
  WorkoutCatalogSlot,
} from './lib/types.js';
